[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
clap = { workspace = true }
anyhow = "1.0"
ctrlc = "3.4"
log = "0.4"
env_logger = "0.11"

[lints]
workspace = true
